services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - database:/var/lib/mysql
    networks:
      - all
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_files:/var/www/inception
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    depends_on:
      - mariadb
    networks:
      - all
    expose:
      - "9000"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/inception
    networks:
      - all
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/database
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress_files

networks:
  all:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt